student={
    'vidhi':{
        "fname":"Vidhi",
        "mname":"Bharatbhai",
        "lname":"Nagar",
        "gender":"Female",
        "area":"rajendrapark",
        "Address":"67 Mukeshnagar society",
        "pincode":382415,
        "age":19,
        "bloodgroup":"B+",
    },
    'mittal':{
        "fname":"Mittal",
        "mname":"Sureshbhai",
        "lname":"Prajapati",
        "gender":"Female",
        "area":"CMC",
        "Address":"78,Hariganga Society",
        "pincode":382415,
        "age":19,
        "bloodgroup":"B+",
    },
    'mansi':{
        "fname":"Mansi",
        "mname":"Shaileshbhai",
        "lname":"Thakor",
        "gender":"Female",
        "area":"rajendrapark",
        "Address":"31,Mukeshnagar Society",
        "pincode":382416,
        "age":20,
        "bloodgroup":"A+",
    },
    'lalit':{
        "fname":"Lalit",
        "mname":"Diparam",
        "lname":"Prajapati",
        "gender":"Male",
        "area":"sheetal chaya",
        "Address":"35,Bina Park",
        "pincode":382418,
        "age":21,
        "bloodgroup":"A-",
    },
    'aditya':{
        "fname":"Aditya",
        "mname":"Rakeshbhai",
        "lname":"Puwar",
        "gender":"Male",
        "area":"sheetal chaya",
        "Address":"33,Tulsi Park",
        "pincode":382415,
        "age":19,
        "bloodgroup":"B+",
    },
    'rishi':{
        "fname":"Rishi",
        "mname":"Rameshbhai",
        "lname":"Prajapati",
        "gender":"Male",
        "area":"sheetal chaya",
        "Address":"50,jogeshwari Society",
        "pincode":382412,
        "age":20,
        "bloodgroup":"B-",
    },
    'riddhi':{
        "fname":"Riddhi",
        "mname":"Nileshbhai",
        "lname":"Nagar",
        "gender":"Female",
        "area":"Vastral",
        "Address":"404,Vrundavan Vatika",
        "pincode":382416,
        "age":30,
        "bloodgroup":"A+",
    },
    'nitanshi':{
        "fname":"Nitanshi",
        "mname":"Nileshbhai",
        "lname":"Prajapati",
        "gender":"Female",
        "area":"Vastral",
        "Address":"302,Annapurna Recedency",
        "pincode":382413,
        "age":5,
        "bloodgroup":"B+",
    },
    'harshiv':{
        "fname":"Nitanshi",
        "mname":"Nileshbhai",
        "lname":"Prajapati",
        "gender":"Female",
        "area":"Vastral",
        "Address":"302,Annapurna Recedency",
        "pincode":382413,
        "age":5,
        "bloodgroup":"B+",
    },

},